name: dartcash
description: A blockchain ctyptocurrency written in Dart language
version: 0.0.1
#homepage: https://www.example.com
#author: alea <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  crypto: 2.0.2
  pointycastle: 0.10.0+5
  bignum: 0.1.0
  base58: 1.0.1
  collection: 1.14.3
  dartson: 0.2.7

dev_dependencies:
  test: ^0.12.0

transformers:
- dartson